name: Build/release

on:
  push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Install Depentent
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y rpm fakeroot
        
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # step5: cleanup artifacts in dist_electron
      #- name: cleanup package lock
      #  run: |
      #    npx rimraf "package-lock.json"

      # step3: npm install
      - name: npm install
        run: |
          npm install

      # step4: build app
      - name: build app
        run: |
          npm run make

      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: 'out/make'

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "out/make/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
